### ISSUE TITLE
Important Parameters Not Accessible 

### ISSUE THREAD

**Issue by YanSte** [pydantic/pydantic-ai#175] opened 2024-12-07 23:05 UTC
I would like to report that several models do not allow access to certain essential parameters, which are crucial for various tasks. 

Here are the parameters in question:

#### Randomness and Diversity:
- **Temperature**
- **Top K**
- **Top P**

#### Length:
- **Response Length**
- **Length Penalty**
- **Stop Sequence**

#### Repetition:
- **Repetition Penalty**

--
### Note on the Groq Model:

For the Groq model, it is important to note that the temperature is set by default to 0. 

---

### Hardcoding Temperature Additional Information:

It is important to note that, depending on the model, you have access to features such as JSON Format or function calling. 

> This means the model will attempt to return responses in JSON format, and yes depending of the model, the prompt used, fine tuned etc..

So depending on your specific task, you may need to adjust parameters (like creativity needs, temperature). 

So for example, if you are generating a summary, a story etc.. You might need to set the temperature to 0.6 to ensure creativity in the response. 

Using JSON format or function call, we expect the response to be in JSON format. (No need to set the temperature to 0)

Temperature to 0 for all responses is not ideal for Json format.
We need to allow for parameter adjustments to better suit the specific needs of each task and its flexibility.

**Comment by samuelcolvin** [comment] 2024-12-08 12:29
Duplicate of #71, let's continue the conversation there.

**Closed by samuelcolvin** 2024-12-08 12:29 UTC
