### ISSUE TITLE
Multiple Responses with Gemini/Vertex LLM

### ISSUE THREAD

**Issue by sandeep540** [pydantic/pydantic-ai#171] opened 2024-12-07 15:02 UTC
Gemini/Vertex has ability to provide multiple response with candidate_count='n' , can you add an ability in Agent API to utilize the same

**Comment by mnmnk43434** [comment] 2024-12-07 15:09
Hello, we tried to solve the issue.

This is what we did:

Implemented the ability to utilize multiple responses with candidate_count in the Agent API. This feature allows the agent to generate and process multiple candidate responses from models like Gemini/Vertex.

You can review changes in this commit: https://github.com/mnmnk43434/pydantic-pydantic-ai-171/commit/1618b0c09010fe5c6518b43bdb96b5f01beb44fe.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by samuelcolvin** [comment] 2024-12-08 12:34
Thanks for creating the issue.

Duplicate of #71, let's continue the conversation there.

**Closed** 2024-12-08 12:35 UTC
