### ISSUE TITLE
Can you add a multi agent example?

### ISSUE THREAD

**Issue by mtessar** [pydantic/pydantic-ai#150] opened 2024-12-05 16:48 UTC
I'm interested in building an agent that uses other agents to complete it's work.  Can you add an example of a multi agent use of PydanticAI?  

[Agency swarm](https://github.com/VRSEN/agency-swarm) has a decent multi agent example that was really helpful when starting out with that framework.

Thanks for putting a great library together!

**Comment by sydney-runkle** [comment] 2024-12-05 18:38
Hi,

Thanks for your question. I'm going to mark this as a dupe of https://github.com/pydantic/pydantic-ai/issues/120 and close accordingly. We'll definitely add an example for this!

**Closed by sydney-runkle** 2024-12-05 18:38 UTC

**Comment by mtessar** [comment] 2024-12-05 18:52
Sorry. I missed that one.
